### ISSUE TITLE
No real timer feature.

### ISSUE THREAD

**Issue by ffejhog** [bearcott/easytimer#1]
You should rename timer to stopwatch and integrate a real timer. Would be much more useful and clear then.

**Comment by bearcott** [comment]
Dear Sir,
actually, sir. If you click and hold it turns into a timer.

Sincerely,
Easytimer CEO

**Comment by ffejhog** [comment]
Oh. Well then make this feature more clear to the user. Otherwise how is anyone going to know it exists?

**Comment by bearcott** [comment]
Well you found out didn't you?

**Comment by ffejhog** [comment]
Becuase you told me. It either needs to be self explanatory or you need to
have some way to tell the users how to use...

**Comment by bearcott** [comment]
I like your logic. Would you like to work here at easytimer LLC? We offer a zero dollar hourly rate for 50% equity.
